UpstreamPath: /tmp/extract/docker-ce
UpstreamRemote: docker/docker-ce
ComponentPath: /tmp/extract/engine-extract
ComponentRemote: docker/engine
ComponentResultRemote: silvin-lubecki/engine-extract
Component: engine
Branch: 17.12
Ancestor: 
ExtractedComponent: /tmp/extract/engine-extract